version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch-7.9.2
    restart: always
    environment:
      - node.name=es-mqtt
      - cluster.name=es-mqtt-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - http.port=9200
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - /opt/mqtt-es/elasticsearch/data:/usr/share/elasticsearch/data
      - /opt/mqtt-es/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 920O:9200
    network_mode: "host"

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana-7.9.2
    restart: always
    environment:
      SERVER_NAME: kibana.docker.local
      ELASTICSEARCH_HOSTS: '["http://localhost:9200"]'
    ports:
      - 5601:5601
    network_mode: "host"
    
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    container_name: logstash-7.9.2
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    network_mode: "host"
    depends_on:
      - elasticsearch
      - activemq

  activemq:
    image: synapticiel/activemq:5.16.0
    container_name: activemq-5.16.0
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms/openwire
      - "61616:61616"
    volumes:
      - /opt/mqtt-es/active-mq/data:/opt/apache-activemq/data
      - /opt/mqtt-es/active-mq/conf:/opt/apache-activemq/cong
    network_mode: "host"